[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pkg-filters"
version = "1.2.0"
description = "Filters for multiple Python frameworks"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }

authors = [
    { name = "Fritill", email = "info@fritill.ae" }
]

# Runtime dependencies
dependencies = [
    "sqlalchemy==2.0.38",
]

#[project.optional-dependencies]

[project.urls]
Homepage = "https://github.com/itqadem-apps/pkg_filters"

[tool.setuptools.packages.find]
where = ["src"]
